language: python
python:
- '3.6'
install:
- pip install requests
script:
- python3 reddit-top-posts.py
env:
  global:
  - secure: vOiKP/th1jwlLZSn9KtlkFurUeLe3mFO4gUXJ3GvwpVyUPT4qOzfHtpNJgbIgdeqhHwYBUCl4uNwmgX402faUnEPgJo2lWVQhw8uWzB5GcPG5EiFz3qV/sj89UkeiCTfOG+kDSYjoRsspcJXIxaYKaR/9uyCahBnc5GiFOOJLq44DP4M3bXe6xqGHuxlJFxFfwYRYbnDJ96SwA+Ghnrz4q3Mu1hMk81rVt0eFuV3bj5N2NjDjv6LnY2n18ANFbvUyto2NpVX+J0SYe9nBWi6JMo14SPBxR7s2sMncKpj3t9j6o3JfOeOWuaOuWkAXMfPKOt7qfJQkd8fLluSpqMDsZ+/HGxNtSG8LpUGAf3E5lKGjkmdmlVzGQXKzeTYcKkm6OgLYhgMOgmBCY1AmOBa4zcR9VAPCOjrA3S8W1C7/13lRz42G5vlgpCFkVB+HoYLdYBYUxKfJsrdFvVH5QVe4YpQjj9UEYFILSde8tWRYW0Rthosu81RWm/0Lu0sABX09sZ4N4OQ99bwj7Dw0rMPcIh6Z+Mk26x1xFpJV1LljtYEjdbVNuQNx3ZhNCVLZXnvo/RrTeOfgggepXGR49n9v9BDkR0AfkGlTM/Pv//vsreWcfCyocIfmzUt9YCdAtjqE2+/zOEKvbJ1DQK2y3B8gA248ZIk/H7X4ZecZr/5nX4=
  - secure: EjjppWrEBonKhTULFaryGAWIwE7hgGElQdTc3QnzkAcEDxWal/r3d50mdb7basgpI3tpVtj93enEIhPsmW26ZGPT8h4VXkAFR/q/GrDnkUgZXVzffF21Z5ARwhQwEyEDo8tdVbzXE1ksMCqRPgl4e2eyZBp0BQXX9ARjZBP7s6ccHoMX2GJiPe+TMG6R9YMG0Rr0VVO7esqhM1sw6N3Pv3S7q+9axmwqeazb/fRajWSeaDCm5tLA/Abzbip4nFCQKF08CHyZ8te+9yLhdq4CZa/zf7rCKobSc6MLNQlIQtXbDVXjsIxvhfZxNHXAYVdMnTkiaCxjBu0ZwcbnRsgaJFjI1gAe0rfnmVPjYbzyWFtYiYfcCC1pu37h+dzhZYD5rsTELqqb4Y4B9ZMXk98tgagTovvrqk2HQ9EF43Og5iWOQ5c7oGuFyNtJ7/rsAW69Q3QWdfCa5qZ1EOGlSJ2JDcn5ZNpQQzIgNop4YPvJzNkfWDN3T2uqM54E/6NfEcPDod9TilE4bGpT5clhANLHG8Z7pR7J3Y/SeBFOFN70F4/hi6F+BI75qB+OnbOZ2b/u4swHjQVK/jiWCSk9U5Yv0klLo2lsCKJ+kEq8lJLzqubNyYIhwR02Zd5uSC2RFxtuX1h0MVQWwJze3vGTlHBklHUmllDJNApwOmiBURGBS+I=
  - SMTP_HOST=mail.alorenzi.eu
  - SMTP_PORT=587
  - SUBS=italy,netsec,devops
  - TO_ADDR=alorenzi@alorenzi.eu
  - FROM_ADDR="Reddit Top Posts <rtp@alorenzi.eu>"